### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/wallgen#15]
- Update README with new command changes

**Comment by angussidney** [comment]
I'm interested in contributing to this issue for Hacktoberfest. Are [these](https://github.com/SubhrajitPrusty/wallgen/commit/780f1927a41b1ac0288b1ac48d5ae54d53c5be71) the only changes which need to be reflected in the README, or have there been some other changes since the last README update?

**Comment by SubhrajitPrusty** [comment]
> I'm interested in contributing to this issue for Hacktoberfest. Are [these](https://github.com/SubhrajitPrusty/wallgen/commit/780f1927a41b1ac0288b1ac48d5ae54d53c5be71) the only changes which need to be reflected in the README, or have there been some other changes since the last README update?

Yes
