### ISSUE TITLE
Add the new shape options to the website

### ISSUE THREAD

**Issue by SubhrajitPrusty** [SubhrajitPrusty/wallgen#32]
For reference, `app.py` is the Flask entry point 

- [x] Add the triangle option
- [x] Add the isometric option

**Comment by Harsh5557** [comment]
I want to work on it.I have worked on flask before.

**Comment by Harsh5557** [comment]
I can start working once you assign it to me

**Comment by SubhrajitPrusty** [comment]
> I can start working once you assign it to me

@Harsh5557 Yes you can start the work

**Comment by Harsh5557** [comment]
How can i test the changes i made .I usually ran flask in debug mode on local host.here its on some server.

**Comment by Harsh5557** [comment]
I don't whether the problem is .I am using notepad++ as my text editor .The indentation changes once i add the two options

**Comment by SubhrajitPrusty** [comment]
fixed by #42

**Comment by SubhrajitPrusty** [comment]
@Harsh5557  no problem. Good work.
