### ISSUE TITLE
Make Smarter Polygons

### ISSUE THREAD

**Issue by ShreyanshDarshan** [SubhrajitPrusty/wallgen#37]
Polygons will look much better if the points that form them lie on edges of the objects in the image.

This can be accomplished by using an edge-detection convolution matrix on the input image to yield an edge-highlighted intermediate image and then using this intermediate image's pixel values as weights for a weighted point generation algorithm.

**Comment by SubhrajitPrusty** [comment]
Yes, you can generate points based on edges - but currently the algorithm is dependent on Delaunay triangulation to determine polygons, which will not differentiate between an edge point and any other point.

Still I am interested to see how it will regardless. Maybe it will work for some pictures.

**Comment by SubhrajitPrusty** [comment]
done

**Comment by SubhrajitPrusty** [comment]
changed Canny detection to Sobel edge detection. Better results.
