### ISSUE TITLE
Error on Python 3.6

### ISSUE THREAD

**Issue by chris13888** [SubhrajitPrusty/wallgen#43]
Sorry, I'm not sure whether this issue is from not installing right or something, but I've gotten the error "failed to create process" no matter when I run it. I use python 3.6 x64 on a Windows computer.

**Comment by SubhrajitPrusty** [comment]
Can you share your processor details? The problem is clear that it is with multiprocessing but I'm not sure what is causing it.

**Comment by chris13888** [comment]
I'm using the CPU i5-8400 without any graphics card. It's a custom build PC.
