### ISSUE TITLE
Feature request: random wallgen

### ISSUE THREAD

**Issue by sl4vkek** [SubhrajitPrusty/wallgen#60]
**Is your feature request related to a problem? Please describe.**
I wanted to create a mastodon bot that posts completely random backgrounds every day, for that i have to write an external program to randomize the flags

**Describe the solution you'd like**
I want a feature where EVERYTHING is randomized. Except for the resolution of course.
Basically it will be another option `wallgen random`. It will pick everything randomly, poly, shape or a slant, a color gradient, all of that. _EVERYTHING_  will be randomized except for the resolution, which will be another flag i.e `wallgen random 2000`.

**Describe alternatives you've considered**
I could write a python script for that, but i think it would be cool if this was a feature.
**Additional context**
Don't have any. Not sure if im allowed to remove this section

**Comment by SubhrajitPrusty** [comment]
Sounds cool. I'll look into it

**Comment by sl4vkek** [comment]
Oh i forgot to mention. I think we should an additional flag to use a seed. i.e for `random.seed(<int>)`
