### ISSUE TITLE
Ready to use Docker image

### ISSUE THREAD

**Issue by WeeSee** [SubhrajitPrusty/wallgen#62]
Great repo! Thank you for providing a Docker image. 

But It would be cool if the Docker image would be available for immediate use on Dockerhub. 

Maybe you can setup a Dockerhub integration that rebuilds the image on Dockerhub on each Github commit.

**Comment by SubhrajitPrusty** [comment]
This is done. You can pull from dockerhub by
`docker pull subhrajitprusty/wallgen` 

Thanks for the input. :)
